---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# emlogit

<!-- badges: start -->
<!-- badges: end -->

`emlogit` implements the EM algorithm for the multinomial logistic regression.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("sou412/emlogit")
```

## Example

`Car` data from `mlogit` package.

```{r warning = FALSE, message = FALSE}
require(emlogit)
require(dplyr)
data(Car, package = 'mlogit')

## prepare data: only allow for indiviual specific covariates
y <- Car %>% select(choice)
Y <- model.matrix(~choice-1, data = y)
X <- Car %>% select(college, hsg2, coml5) %>% data.matrix()
```

```{r}
## fit
fit <- emlogit(Y = Y, X = X)
summary(fit)

## predicted probability
prob <- predict(fit)
head(prob)
```


```{r}
## multinomial outcome 
data(japan, package = "MNP")
head(japan)

Y <- japan %>% select(LDP, NFP, SKG, JCP) %>% data.matrix()
X <- japan %>% select(gender, education, age) %>% data.matrix()

fit <- emlogit(Y = Y, X = X)
summary(fit)
```
