# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' observed log-likelihood
#' @keyword internal
log_likelihood <- function(Y, X, B, mu0, Z0) {
    .Call('_emlogit_log_likelihood', PACKAGE = 'emlogit', Y, X, B, mu0, Z0)
}

emlogit_run <- function(Y, X, B, tol, max_iter, mu0, Z0, verbose) {
    .Call('_emlogit_emlogit_run', PACKAGE = 'emlogit', Y, X, B, tol, max_iter, mu0, Z0, verbose)
}

